# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Eliminate delay going to vim normal mode
KEYTIMEOUT=1

# Bind escape so it doesn't block in normal mode
noop () { }
zle -N noop
bindkey -M vicmd '\e' noop


# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

export BAT_THEME="ansi"

export VI_MODE_SET_CURSOR="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

setopt AUTO_PARAM_SLASH # add trailing slashes to dirs on completion
zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path "${ZDOTDIR:-$HOME}/.zcompcache"
zstyle ':completion:*' squeeze-slashes true

# 0 -- vanilla completion (abc => abc)
# 1 -- smart case completion (abc => Abc)
# 2 -- word flex completion (abc => A-big-Car)
# 3 -- full flex completion (abc => ABraCadabra)
zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
#  'r:|?=** m:{a-z\-}={A-Z\_}'

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell

fpath=(~/.oh-my-zsh/custom/plugins/zsh-completions/src $fpath)
# Note, zsh-syntax-highlighting should be the last plugin loaded
plugins=(git vi-mode zsh-cargo-completion zsh-completions copybuffer dirhistory zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor
export EDITOR='nvim'


timer() {
  start="$(($(date +%s) + $1))"
  while [ "$start" -ge `date +%s` ]; do
      time="$(( $start - `date +%s` ))"
      printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
  done
}


# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
alias v="nvim"
alias vim="nvim"
alias ls="exa --icons"
alias l="exa --icons"
alias bat="batcat"
alias m="monenv"
alias sl="ls"
alias s="monenv && cd src && clear"
alias lg="lazygit"
alias reload=". ~/.zshrc"
alias gs="git status"
alias c="cd"
alias e="exit"
alias f="find . | grep -i"
alias fr="rg -i"
alias path='tr ":" "\n" <<< $PATH'
alias lock="xdg-screensaver lock"

export MANPAGER="sh -c 'col -bx | batcat -l man -p'"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.config/powerlevel10k/p10k.zsh ]] || source ~/.config/powerlevel10k/p10k.zsh

